# Notebook 1 : Découverte de Pandas

In [ ]:
import pandas as pd

## Iris

Nous considérons le jeu de données connu sous le nom des [Iris de Fisher](https://fr.wikipedia.org/wiki/Iris_de_Fisher). Répondez aux questions suivantes à l'aide du module Pandas.

1. Charger le jeu de données dans un dataframe `iris` à partir du fichier `iris.csv` et afficher le dataframe.

In [15]:
import pandas as pd
df = pd.read_csv("../data/iris.csv")
df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

2. Sélectionner les variables `PetalWidth` et `Species`.

In [16]:
print(df[["PetalWidth", "Species"]])

     PetalWidth    Species
0           0.2     setosa
1           0.2     setosa
2           0.2     setosa
3           0.2     setosa
4           0.2     setosa
..          ...        ...
145         2.3  virginica
146         1.9  virginica
147         2.0  virginica
148         2.3  virginica
149         1.8  virginica

[150 rows x 2 columns]

3. Extraire le sous-dataframe qui contient uniquement les iris des espèces `versicolor` ou `virginica`.

In [17]:
print(df[(df["Species"] == "virginica") | (df["Species"] == "setosa") ])

     SepalLength  SepalWidth  PetalLength  PetalWidth    Species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[100 rows x 5 columns]

4. Compter le nombre d'iris de l'espèce `setosa`.

In [50]:
# df[df["Species"] == "setosa"].count()
len(df[df["Species"] == "setosa"])

50

5. Calculer la moyenne de la variable `PetalWidth` pour les iris de l'espèce `versicolor`.

In [ ]:
df[df["Species"] == "versicolor"]["PetalWidth"].mean()

np.float64(1.3259999999999998)

6. Ajouter une variable `SumWidth` qui contient la somme des variables `PetalWidth` et `SepalWidth`.

In [55]:
df["Sumwidth"] = df.PetalWidth + df.SepalWidth

7. Calculer la moyenne et la variance de la variable `SepalLength` pour chaque espèce.

In [57]:
df[["SepalLength"]].groupby(df.Species).agg(["mean", "var"])

           SepalLength
                  mean       var
Species
setosa           5.006  0.124249
versicolor       5.936  0.266433
virginica        6.588  0.404343

8. Calculer la moyenne de toutes les variables pour chaque espèce. Afficher le résultat au format large et au format long.

In [59]:
moy = df[["SepalLength", "SepalWidth", "PetalLength", "PetalWidth"]].groupby(df.Species).mean()
#transformation format long
print(
    moy.reset_index()
    .melt(id_vars = ["Species"], value_name = "measure")
)

       Species     variable  measure
0       setosa  SepalLength    5.006
1   versicolor  SepalLength    5.936
2    virginica  SepalLength    6.588
3       setosa   SepalWidth    3.428
4   versicolor   SepalWidth    2.770
5    virginica   SepalWidth    2.974
6       setosa  PetalLength    1.462
7   versicolor  PetalLength    4.260
8    virginica  PetalLength    5.552
9       setosa   PetalWidth    0.246
10  versicolor   PetalWidth    1.326
11   virginica   PetalWidth    2.026

## Houston flights

Nous considérons le jeux de données `hflights` relatif à des vols au départ des aéroports *Houston George Bush Intercontinental Airport* (IAH) et *William P. Hobby Airport* (HOU).

1. Charger le jeu de données dans un dataframe `hflights` à partir du fichier `hflights.csv`

In [71]:
hflights = pd.read_csv("../data/hflights.csv")

2. Sélectionner les variable `Dest`, `Distance`, `TaxiIn` et `TaxiOut` avec la méthode `filter`.

In [72]:
hflights.filter(items = ["Dest", "Distance", "TaxiIn", "TaxiOut"])

       Dest  Distance  TaxiIn  TaxiOut
0       DFW       224     7.0     13.0
1       DFW       224     6.0      9.0
2       DFW       224     5.0     17.0
3       DFW       224     9.0     22.0
4       DFW       224     9.0      9.0
...     ...       ...     ...      ...
227491  TPA       781     5.0     11.0
227492  TPA       781     4.0      9.0
227493  TUL       453     4.0     14.0
227494  TUL       453     3.0      9.0
227495  TUL       453     3.0     11.0

[227496 rows x 4 columns]

3. Sélectionner les variables `DepTime`, `ArrTime`, `ActualElapsedTime` et `AirTime` avec la méthode `filter` et le paramètre `like`.

In [73]:
hflights.filter(like = "Time")

        DepTime  ArrTime  ActualElapsedTime  AirTime
0        1400.0   1500.0               60.0     40.0
1        1401.0   1501.0               60.0     45.0
2        1352.0   1502.0               70.0     48.0
3        1403.0   1513.0               70.0     39.0
4        1405.0   1507.0               62.0     44.0
...         ...      ...                ...      ...
227491   1818.0   2111.0              113.0     97.0
227492   2047.0   2334.0              107.0     94.0
227493    912.0   1031.0               79.0     61.0
227494    656.0    812.0               76.0     64.0
227495   1600.0   1713.0               73.0     59.0

[227496 rows x 4 columns]

4. Ajouter une variable `ActualGroundTime` qui correspond à `ActualElapsedTime` moins `AirTime`.

In [74]:
hflights["ActualGroundTime"] = hflights.ActualElapsedTime - hflights.AirTime
hflights.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,ActualGroundTime
0,2011,1,1,6,1400.0,1500.0,AA,428,N576AA,60.0,...,0.0,IAH,DFW,224,7.0,13.0,0,NaN,0,20.0
1,2011,1,2,7,1401.0,1501.0,AA,428,N557AA,60.0,...,1.0,IAH,DFW,224,6.0,9.0,0,NaN,0,15.0
2,2011,1,3,1,1352.0,1502.0,AA,428,N541AA,70.0,...,-8.0,IAH,DFW,224,5.0,17.0,0,NaN,0,22.0
3,2011,1,4,2,1403.0,1513.0,AA,428,N403AA,70.0,...,3.0,IAH,DFW,224,9.0,22.0,0,NaN,0,31.0
4,2011,1,5,3,1405.0,1507.0,AA,428,N492AA,62.0,...,5.0,IAH,DFW,224,9.0,9.0,0,NaN,0,18.0

5. Ajouter une variable `AverageSpeed` qui donne la vitesse moyenne du vol et ordonner la table selon les valeurs décroissantes de cette variable.

In [79]:
hflights["AverageSpeed"] = hflights.Distance / (hflights.AirTime)
hflights.sort_values(by = "AverageSpeed")

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,ActualGroundTime,Speed,AverageSpeed
78149,2011,5,12,4,1136.0,1329.0,CO,741,N76288,113.0,...,AUS,140,6.0,22.0,0,NaN,0,28.0,0.725389,1.647059
78528,2011,5,10,2,1947.0,2125.0,CO,1441,N17229,98.0,...,AUS,140,4.0,15.0,0,NaN,0,19.0,0.786517,1.772152
78191,2011,5,12,4,1132.0,1346.0,CO,1583,N14639,134.0,...,AUS,140,7.0,50.0,0,NaN,0,57.0,0.654206,1.818182
80764,2011,5,10,2,1954.0,2126.0,WN,819,N705SW,92.0,...,AUS,148,7.0,8.0,0,NaN,0,15.0,0.860465,1.922078
156518,2011,9,16,5,733.0,927.0,CO,1155,N16646,114.0,...,SAT,191,3.0,19.0,0,NaN,0,22.0,0.984536,2.076087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227134,2011,12,4,7,1050.0,1843.0,WN,1797,N791SW,NaN,...,BWI,1246,6.0,11.0,0,NaN,1,NaN,1.571248,NaN
227153,2011,12,4,7,NaN,NaN,WN,2387,N928WN,NaN,...,DAL,239,NaN,NaN,1,A,0,NaN,NaN,NaN
227271,2011,12,5,1,NaN,NaN,WN,38,N604SW,NaN,...,DAL,239,NaN,NaN,1,A,0,NaN,NaN,NaN
227302,2011,12,5,1,819.0,1221.0,WN,269,N665WN,NaN,...,JAN,359,6.0,9.0,0,NaN,1,NaN,0.893035,NaN
227394,2011,12,6,2,NaN,NaN,WN,16,N362SW,NaN,...,DAL,239,NaN,NaN,1,A,0,NaN,NaN,NaN

6. Sélectionner les vols à destination de `JFK`.

In [80]:
hflights[hflights["Dest"] == "JFK"]

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,...,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,ActualGroundTime,Speed,AverageSpeed
304,2011,1,1,6,654.0,1124.0,B6,620,N324JB,210.0,...,JFK,1428,6.0,23.0,0,NaN,0,29.0,3.038298,7.889503
305,2011,1,1,6,1639.0,2110.0,B6,622,N324JB,211.0,...,JFK,1428,12.0,11.0,0,NaN,0,23.0,3.031847,7.595745
306,2011,1,2,7,703.0,1113.0,B6,620,N324JB,190.0,...,JFK,1428,6.0,12.0,0,NaN,0,18.0,3.482927,8.302326
307,2011,1,2,7,1604.0,2040.0,B6,622,N324JB,216.0,...,JFK,1428,9.0,31.0,0,NaN,0,40.0,3.275229,8.113636
308,2011,1,3,1,659.0,1100.0,B6,620,N229JB,181.0,...,JFK,1428,3.0,12.0,0,NaN,0,15.0,3.238095,8.602410
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208752,2011,12,29,4,1541.0,1959.0,B6,622,N206JB,198.0,...,JFK,1428,7.0,8.0,0,NaN,0,15.0,3.416268,7.803279
208753,2011,12,30,5,634.0,1040.0,B6,620,N317JB,186.0,...,JFK,1428,4.0,12.0,0,NaN,0,16.0,3.517241,8.400000
208754,2011,12,30,5,1541.0,1957.0,B6,622,N296JB,196.0,...,JFK,1428,5.0,10.0,0,NaN,0,15.0,3.432692,7.889503
208755,2011,12,31,6,831.0,1251.0,B6,620,N247JB,200.0,...,JFK,1428,5.0,20.0,0,NaN,0,25.0,3.400000,8.160000
208756,2011,12,31,6,1544.0,2009.0,B6,622,N323JB,205.0,...,JFK,1428,4.0,11.0,0,NaN,0,15.0,3.070968,7.515789

7. Compter le nombre de vols à destination de `JFK`.

In [81]:
len(hflights[hflights["Dest"] == "JFK"])

695

8. Agréger les données `hflights` pour obtenir :
- `n` : le nombre total de vols,
- `n_dest`: le nombre total de destinations distinctes,
- `n_carrier` : le nombre total de compagnies distinctes.

In [ ]:
hflights.
.agg( 
    n = pd.Namegg(column="FlightNum", aggfunc = "count"),
    n_dest = pd.Series.unique
    n_carrier" : "sum"
    }
)

KeyError: "None of [Index(['n', 'n_dest', 'n_carrier'], dtype='object')] are in the [columns]"

9. Agréger les données des vols de la compagnie `AA` pour obtenir :
- le nombre total de vols,
- le nombre total de vols annulés,
- la valeur moyenne de `ArrDelay`.

10. Calculer pour chaque compagnie :
- le nombre total de vols,
- la valeur moyenne de `AirTime`.

11. Ordonner les compagnies en fonction des retards moyens au départ.