# Notebook 5 : Web scraping

In [ ]:
# Décommenter la ligne suivante pour installer lxml (nécessaire pour read_html)
# %pip install lxml

In [1]:
import pandas as pd
import requests

from bs4 import BeautifulSoup

## Bonsaïs

Le site [Umi Zen Bonsai](https://umizenbonsai.com/) est une boutique de vente en ligne dédiée aux bonsaïs. Les conifères sont disponible sur la page web [https://umizenbonsai.com/shop/bonsai/coniferes/](https://umizenbonsai.com/shop/bonsai/coniferes/). Comme beaucoup d'autres sites, l'information est organisée en blocs dans lesquels il est possible de récupérer des données.

Pour scraper ce type de site, le processus consiste à capturer les blocs dans un premier temps, puis à en extraire les données.

1. Récupérer le contenu de la page avec `requests` et passer le résultat au parser de `BeautifulSoup`.

In [31]:
url = "https://umizenbonsai.com/shop/bonsai/coniferes/"
url_base = "https://umizenbonsai.com/shop/bonsai/coniferes/"
#url_spec = "/wiki/Cate_Blanchett"

r = requests.get(url, headers={"User-Agent": "CepeBot"})

# check ok page web récupérée
if r.status_code == 200:
    print("Page web récupérée")
else:
    print(f"Erreur {r.status_code}")

 #contenu de la page : r.text

soup = BeautifulSoup(r.text, "html.parser") # HTML parser de Python
print(str(soup)[:700] + "...")

Page web récupérée
<!DOCTYPE html>

<html class="html" lang="fr-FR">
<head>
<meta charset="utf-8"/>
<link href="https://gmpg.org/xfn/11" rel="profile"/>
<meta content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" name="robots">
<link as="font" crossorigin="" data-wpacu-preload-google-font="1" href="https://fonts.gstatic.com/s/montserrat/v26/JTUQjIg1_i6t8kCHKm459WxRyS7m0dR9pA.woff2" rel="preload"/>
<link as="font" crossorigin="" data-wpacu-preload-google-font="1" href="https://fonts.gstatic.com/s/montserrat/v26/JTUSjIg1_i6t8kCHKm459WlhyyTh89Y.woff2" rel="preload"/>
<link as="font" crossorigin="" data-wpacu-preload-google-font="1" href="https://fonts.gstatic.com/s/montserrat/v26/...

2. Écrire un sélecteur CSS pour capturer les éléments `li` qui contiennent les blocs correspondants aux bonsaïs. Vérifier sur le site que le nombre de bonsaïs affichés correspond.

In [ ]:

#partie la plus technique
css_selector = "ul.products li.entry"
#css_selector = "div.product-inner ul.woo-entry-inner li.price-wrap"
# on récupère les infos des 5 bonzai de la page
bonzai = soup.select(css_selector)
print(bonzai)
len(bonzai) # on a bien 5 bonzai

[<li class="entry has-media col span_1_of_4 owp-content-center owp-thumbs-layout-horizontal owp-btn-big owp-tabs-layout-horizontal circle-sale product type-product post-55126 status-publish first instock product_cat-coniferes product_cat-tous-les-bonsai product_tag-bonsai has-post-thumbnail taxable shipping-taxable product-type-simple">
<div class="product-inner clr">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/"><img alt="Bonsai Cyprès du Japon – 33cm" class="woo-entry-image-main" decoding="async" fetchpriority="high" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
<ul class="woo-entry-inner clr"><li class="image-wrap">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/"><img alt="Bonsai Cyprès du Japon – 33cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-cypres-du-japon-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
</li><li class="price-wrap">
<span class="price"><span class="woocommerce-Price-amount amount"><bdi>150.00<span class="woocommerce-Price-currencySymbol">€</span></bdi></span></span>
</li><li class="btn-wrap clr"><a aria-describedby="woocommerce_loop_add_to_cart_link_describedby_55126" aria-label="En savoir plus sur “Bonsai Cyprès du Japon - 33cm”" class="button product_type_simple" data-product_id="55126" data-product_sku="" data-quantity="1" data-success_message="" href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/" rel="nofollow">Retrait à Hossegor</a> <span class="screen-reader-text" id="woocommerce_loop_add_to_cart_link_describedby_55126">
</span>
</li><li class="title"><h2><a href="https://umizenbonsai.com/vente/bonsai-cypres-du-japon/">Bonsai Cyprès du Japon – 33cm</a></h2></li><li class="rating"></li></ul></div><!-- .product-inner .clr --></li>, <li class="entry has-media col span_1_of_4 owp-content-center owp-thumbs-layout-horizontal owp-btn-big owp-tabs-layout-horizontal circle-sale product type-product post-54545 status-publish instock product_cat-coniferes product_cat-tous-les-bonsai product_tag-bonsai product_tag-france has-post-thumbnail taxable shipping-taxable product-type-simple">
<div class="product-inner clr">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-genevrier-phenicie/"><img alt="Bonsai Genévrier de Phénicie – 67cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
<ul class="woo-entry-inner clr"><li class="image-wrap">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-genevrier-phenicie/"><img alt="Bonsai Genévrier de Phénicie – 67cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-genevrier-phenicie-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
</li><li class="price-wrap">
<span class="price"><span class="woocommerce-Price-amount amount"><bdi>450.00<span class="woocommerce-Price-currencySymbol">€</span></bdi></span></span>
</li><li class="btn-wrap clr"><a aria-describedby="woocommerce_loop_add_to_cart_link_describedby_54545" aria-label="En savoir plus sur “Bonsai Genévrier de Phénicie - 67cm”" class="button product_type_simple" data-product_id="54545" data-product_sku="" data-quantity="1" data-success_message="" href="https://umizenbonsai.com/vente/bonsai-genevrier-phenicie/" rel="nofollow">Retrait à Hossegor</a> <span class="screen-reader-text" id="woocommerce_loop_add_to_cart_link_describedby_54545">
</span>
</li><li class="title"><h2><a href="https://umizenbonsai.com/vente/bonsai-genevrier-phenicie/">Bonsai Genévrier de Phénicie – 67cm</a></h2></li><li class="rating"></li></ul></div><!-- .product-inner .clr --></li>, <li class="entry has-media col span_1_of_4 owp-content-center owp-thumbs-layout-horizontal owp-btn-big owp-tabs-layout-horizontal circle-sale product type-product post-69594 status-publish instock product_cat-coniferes product_cat-tous-les-bonsai product_tag-bonsai product_tag-france has-post-thumbnail taxable shipping-taxable product-type-simple">
<div class="product-inner clr">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-if-commun-3/"><img alt="Bonsai If Commun – 38cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
<ul class="woo-entry-inner clr"><li class="image-wrap">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-if-commun-3/"><img alt="Bonsai If Commun – 38cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-3-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
</li><li class="price-wrap">
<span class="price"><span class="woocommerce-Price-amount amount"><bdi>450.00<span class="woocommerce-Price-currencySymbol">€</span></bdi></span></span>
</li><li class="btn-wrap clr"><a aria-describedby="woocommerce_loop_add_to_cart_link_describedby_69594" aria-label="En savoir plus sur “Bonsai If Commun - 38cm”" class="button product_type_simple" data-product_id="69594" data-product_sku="" data-quantity="1" data-success_message="" href="https://umizenbonsai.com/vente/bonsai-if-commun-3/" rel="nofollow">Retrait à Hossegor</a> <span class="screen-reader-text" id="woocommerce_loop_add_to_cart_link_describedby_69594">
</span>
</li><li class="title"><h2><a href="https://umizenbonsai.com/vente/bonsai-if-commun-3/">Bonsai If Commun – 38cm</a></h2></li><li class="rating"></li></ul></div><!-- .product-inner .clr --></li>, <li class="entry has-media col span_1_of_4 owp-content-center owp-thumbs-layout-horizontal owp-btn-big owp-tabs-layout-horizontal circle-sale product type-product post-57381 status-publish last outofstock product_cat-coniferes product_cat-tous-les-bonsai product_tag-bonsai product_tag-france has-post-thumbnail taxable shipping-taxable product-type-simple">
<div class="product-inner clr">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-if-commun-2/"><img alt="Bonsai If Commun – 58cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
<ul class="woo-entry-inner clr"><li class="image-wrap"> <div class="outofstock-badge">
					Épuisé				</div><!-- .product-entry-out-of-stock-badge -->
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-if-commun-2/"><img alt="Bonsai If Commun – 58cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-if-commun-2-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
</li><li class="price-wrap">
<span class="price"><span class="woocommerce-Price-amount amount"><bdi>1,350.00<span class="woocommerce-Price-currencySymbol">€</span></bdi></span></span>
</li><li class="btn-wrap clr"><a aria-describedby="woocommerce_loop_add_to_cart_link_describedby_57381" aria-label="En savoir plus sur “Bonsai If Commun - 58cm”" class="button product_type_simple" data-product_id="57381" data-product_sku="" data-quantity="1" data-success_message="" href="https://umizenbonsai.com/vente/bonsai-if-commun-2/" rel="nofollow">Hors stock</a> <span class="screen-reader-text" id="woocommerce_loop_add_to_cart_link_describedby_57381">
</span>
</li><li class="title"><h2><a href="https://umizenbonsai.com/vente/bonsai-if-commun-2/">Bonsai If Commun – 58cm</a></h2></li><li class="rating"></li></ul></div><!-- .product-inner .clr --></li>, <li class="entry has-media col span_1_of_4 owp-content-center owp-thumbs-layout-horizontal owp-btn-big owp-tabs-layout-horizontal circle-sale product type-product post-79593 status-publish first instock product_cat-coniferes product_cat-tous-les-bonsai product_tag-bonsai product_tag-france has-post-thumbnail taxable shipping-taxable product-type-simple">
<div class="product-inner clr">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-pin-sylvestre-1/"><img alt="Bonsai Pin Sylvestre – 38cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
<ul class="woo-entry-inner clr"><li class="image-wrap">
<div class="woo-entry-image clr">
<a class="woocommerce-LoopProduct-link" href="https://umizenbonsai.com/vente/bonsai-pin-sylvestre-1/"><img alt="Bonsai Pin Sylvestre – 38cm" class="woo-entry-image-main" decoding="async" height="800" itemprop="image" sizes="(max-width: 800px) 100vw, 800px" src="https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop.jpg" srcset="https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop.jpg 800w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-150x150.jpg 150w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-300x300.jpg 300w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-768x768.jpg 768w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-600x600.jpg 600w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-100x100.jpg 100w, https://umizenbonsai.com/wp-content/uploads/bonsai-pin-sylvestre-1-umi-zen-bonsai-shop-64x64.jpg 64w" width="800"/></a> </div><!-- .woo-entry-image -->
</li><li class="price-wrap">
<span class="price"><span class="woocommerce-Price-amount amount"><bdi>1,250.00<span class="woocommerce-Price-currencySymbol">€</span></bdi></span></span>
</li><li class="btn-wrap clr"><a aria-describedby="woocommerce_loop_add_to_cart_link_describedby_79593" aria-label="En savoir plus sur “Bonsai Pin Sylvestre - 38cm”" class="button product_type_simple" data-product_id="79593" data-product_sku="" data-quantity="1" data-success_message="" href="https://umizenbonsai.com/vente/bonsai-pin-sylvestre-1/" rel="nofollow">Retrait à Hossegor</a> <span class="screen-reader-text" id="woocommerce_loop_add_to_cart_link_describedby_79593">
</span>
</li><li class="title"><h2><a href="https://umizenbonsai.com/vente/bonsai-pin-sylvestre-1/">Bonsai Pin Sylvestre – 38cm</a></h2></li><li class="rating"></li></ul></div><!-- .product-inner .clr --></li>]

5

In [ ]:
#css_selector = "ul.products li" # on récupère le niveau du haut, tous les li à n'importe quel niveau sous ul.product
#bonzai2 = soup.select(css_selector)
#print(bonzai2)

In [48]:
# dans chaque bloc de 5 bonzai, on réutilise select pour extraire la valeurs qui m'intéressent = prix
# on essaie dans le 1er bloc d'abord pour tester
bonzai[0].select("li.price-wrap")[0].text

# pour affiner et récupérer uniquemet le prix sans les retours à la ligne etc
bonzai[0].select("li.price-wrap bdi")[0].text

# pour affiner encore et retirer le dernier terme (sigle euro) 
# + transformer en float car sinon retourne une chaîne de caractères
float(bonzai[0].select("li.price-wrap bdi")[0].text[:-1])

150.0

3. Écrire une fonction qui prend un bloc de la liste précédente et retourne un tuple contenant le nom, le prix et le lien de description du bonsaï.

In [ ]:
# voir correction - faux
def bonsai_data[bonzai]:
    bonzai_a bonzai.select("li.title a")[0]
    nom = bonzai_a.text
    url = bonzai_a.attrs["href"]
    prix = float(var_bonzai.select("li.price-wrap bdi")[0].text[:-1])


"""var_bonzai = bonzai[0]
float(var_bonzai.select("li.price-wrap bdi")[0].text[:-1])

tab_prix = []
for i in range(5):
    prix = float(bonzai[i].select("li.price-wrap bdi")[0].text[:-1])
    tab_prix.append(prix)

tab_prix"""

NameError: name 'bonsai' is not defined

4. Utiliser les deux questions précédentes pour construire un dataframe contenant les données des bonsaïs.

In [ ]:
# voir correction - faux
bonsais_fr = pd.Dataframe(
    (bonsai_data(bonzai) for bonsai in bonsais)
)

5. (*Bonus*) Écrire une fonction pour récupérer la provenance, le feuilage et les dimension du bonsaï à partir du lien de description. Utiliser cette fonction pour ajouter des colonnes au dataframe précédent

## Trampoline

Le trampoline est un sport olympique depuis les jeux de Sydney en 2000. La page suivante contient les listes des hommes et des femmes ayant obtenu une médaille olympique dans cette discipline :
[https://fr.wikipedia.org/wiki/Liste_des_m%C3%A9daill%C3%A9s_olympiques_au_trampoline](https://fr.wikipedia.org/wiki/Liste_des_m%C3%A9daill%C3%A9s_olympiques_au_trampoline)

Un tableau est contenu dans un élément `table` avec des balises pour les lignes `tr`, pour les colonnes `th`, pour les cellules `td`, ... Cela peut être fastidieux à scraper et très répétitif. Heureusement, Pandas propose la fonction `read_html` pour récupérer des tableaux sous forme de dataframes à partir d'une page web.

1. Récupérer le contenu de la page des médaillés olympiques au trampoline avec `requests` en passant un *User Agent* dans les en-têtes `headers`. Utiliser ensuite la fonction `read_html` de Pandas directement sur le contenu textuel de la page. Combien de dataframes sont récupérés ?

2. Extraire de la liste précédente les dataframes des médailles masculines et féminines.

3. À partir de ces dataframes, compter combien chaque pays a reçu de médailles d'or, d'argent et de bronze.

4. (*Bonus*) Construire un dataframe contenant, pour chaque pays, le nombre de médailles d'or, d'argent et de bronze ainsi que le nombre total de médailles. Classer ce dataframe dans l'ordre usuel en fonction d'abord du nombre de médailles d'or, puis du nombre de médailles d'argent et enfin du nombre de médailles de bronze. Comparer le résultat avec le tableau des médailles sur la page [https://fr.wikipedia.org/wiki/Trampoline_aux_Jeux_olympiques](https://fr.wikipedia.org/wiki/Trampoline_aux_Jeux_olympiques).

## Cate Blanchett

Dans le cours, nous avons essayé de trouver avec quels acteurs Cate Blanchett a joué le plus au cours des années 2000. Pour cela, nous avons récupéré la liste des pages Wikipedia des films où elle tient un rôle avec le code suivant :

In [105]:
url_wikipedia = "https://fr.wikipedia.org"
url_blanchett = url_wikipedia + "/wiki/Cate_Blanchett"

# Ne pas oublier le User Agent pour les pages Wikipedia
r_blanchett = requests.get(url_blanchett, headers={"User-Agent": "CepeBot"})

# check récup page web
assert r_blanchett.status_code == 200, f"Erreur {r_blanchett.status_code}"

soup_blanchett = BeautifulSoup(r_blanchett.text, "html.parser")

# css
selector_films = "#mw-content-text div ul:nth-of-type(3) li i a"
films_blanchett = soup_blanchett.select(selector_films)

# mise enforme de la liste des films
films_data = [
    {
        "titre": film.attrs["title"],
        "url_wikipedia": url_wikipedia + film.attrs["href"]
    }
    for film in films_blanchett
    if not (
        film.attrs.get("class") == ["new"] # Film sans page
        or film.attrs["title"] == "Galadriel" # Mauvais lien
    )
]

films = pd.DataFrame(films_data)

films

,titre,url_wikipedia
0,Les Larmes d'un homme,https://fr.wikipedia.org/wiki/Les_Larmes_d%27u...
1,Intuitions,https://fr.wikipedia.org/wiki/Intuitions
2,"Bandits (film, 2001)","https://fr.wikipedia.org/wiki/Bandits_(film,_2..."
3,Le Seigneur des anneaux : La Communauté de l'a...,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...
4,Charlotte Gray,https://fr.wikipedia.org/wiki/Charlotte_Gray
5,Terre Neuve (film),https://fr.wikipedia.org/wiki/Terre_Neuve_(film)
6,"Heaven (film, 2002)","https://fr.wikipedia.org/wiki/Heaven_(film,_2002)"
7,Le Seigneur des anneaux : Les Deux Tours,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...
8,Veronica Guerin (film),https://fr.wikipedia.org/wiki/Veronica_Guerin_...
9,Coffee and Cigarettes,https://fr.wikipedia.org/wiki/Coffee_and_Cigar...
10,Les Disparues,https://fr.wikipedia.org/wiki/Les_Disparues
11,Le Seigneur des anneaux : Le Retour du roi,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...
12,La Vie aquatique,https://fr.wikipedia.org/wiki/La_Vie_aquatique
13,Aviator,https://fr.wikipedia.org/wiki/Aviator
14,"Little Fish (film, 2005)",https://fr.wikipedia.org/wiki/Little_Fish_(fil...
15,"Babel (film, 2006)","https://fr.wikipedia.org/wiki/Babel_(film,_2006)"
16,The Good German,https://fr.wikipedia.org/wiki/The_Good_German
17,Chronique d'un scandale,https://fr.wikipedia.org/wiki/Chronique_d%27un...
18,Hot Fuzz,https://fr.wikipedia.org/wiki/Hot_Fuzz
19,I'm Not There,https://fr.wikipedia.org/wiki/I%27m_Not_There
20,Elizabeth : L'Âge d'or,https://fr.wikipedia.org/wiki/Elizabeth_:_L%27...
21,Ponyo sur la falaise,https://fr.wikipedia.org/wiki/Ponyo_sur_la_fal...
22,Indiana Jones et le Royaume du crâne de cristal,https://fr.wikipedia.org/wiki/Indiana_Jones_et...
23,L'Étrange Histoire de Benjamin Button (film),https://fr.wikipedia.org/wiki/L%27%C3%89trange...

Le sélecteur CSS que nous avons utilisé ne permettait pas d'obtenir la réponse à notre question car il ne capturait pas toutes les listes d'acteurs (organisation différente pour *Coffee and Cigarettes*, double colonne pour *Aviator*, ...). En effet, les pages Wikipedia des films ne sont pas uniformes et il n'est pas possible d'extraire la distribution de tous les films avec le même sélecteur.

Pour remédier à cela, nous proposons ici d'aller scraper la liste des acteurs sur le site [TMDB](https://www.themoviedb.org/) (*The Movie Database*) dont les pages obéissent toutes à la même organisation. Les pages Wikipedia relatives à des films contiennent toutes un lien externe vers ce site.

1. Pour chaque film, scraper la page Wikipedia pour récupérer le lien vers la page TMDB associée et déduire le lien du casting complet qui ser ajouté le dans une nouvelle colonne du dataframe `films`.

In [ ]:
# essai pour commencer - pour le film Coffee and Cigarettes
film_url = "https://fr.wikipedia.org/wiki/Coffee_and_Cigarettes"

r = requests.get(film_url, headers={"User-Agent": "CepeBot"})

# check ok page web récupérée
if r.status_code == 200:
    print("Page web récupérée")
else:
    print(f"Erreur {r.status_code}")

film_soup = BeautifulSoup(r.text, "html.parser") # HTML parser de Python

css_selector = "a.eternal"
coffee = film_soup.select(css_selector)
coffee

Page web récupérée

[]

In [ ]:
# généralisation à tous les films => fonction
def get_tmdb_url(film_url):
    r =requests.get(film_url, headers={"User-Agent": "CepeBot"})
    r.raise_for_status()

    film_soup = BeautifulSoup(r.text, "html.parser")

    found_url = None
    
    for external_link in film_soup.select("a.external"):
        external_url = external_link.attrs["href"]
        if "themoviedb" in external_url:
            found_url = external_url
            break
    return found_url

In [ ]:
# pour chaque film, à partir du lien wikipédia, on récupère le lien vers le site tmdb 
# car le site est mieux structuré et on récupère les infos bcp plus simplement

films["tmdb_url"] = films["url_wikipedia"].apply(get_tmdb_url)
films["tmdb_cast_url"] = (
    films["tmdb_url"]
    .apply(
        lambda tmdb_url : tmdb_url + "/cast" if tmdb_url is not None else None
    )
)

In [112]:
films

,titre,url_wikipedia,tmdb_url,tmdb_cast_url
0,Les Larmes d'un homme,https://fr.wikipedia.org/wiki/Les_Larmes_d%27u...,https://www.themoviedb.org/movie/29572,https://www.themoviedb.org/movie/29572/cast
1,Intuitions,https://fr.wikipedia.org/wiki/Intuitions,https://www.themoviedb.org/movie/2046,https://www.themoviedb.org/movie/2046/cast
2,"Bandits (film, 2001)","https://fr.wikipedia.org/wiki/Bandits_(film,_2...",https://www.themoviedb.org/movie/3172,https://www.themoviedb.org/movie/3172/cast
3,Le Seigneur des anneaux : La Communauté de l'a...,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...,https://www.themoviedb.org/movie/120,https://www.themoviedb.org/movie/120/cast
4,Charlotte Gray,https://fr.wikipedia.org/wiki/Charlotte_Gray,https://www.themoviedb.org/movie/12660,https://www.themoviedb.org/movie/12660/cast
5,Terre Neuve (film),https://fr.wikipedia.org/wiki/Terre_Neuve_(film),https://www.themoviedb.org/movie/6440,https://www.themoviedb.org/movie/6440/cast
6,"Heaven (film, 2002)","https://fr.wikipedia.org/wiki/Heaven_(film,_2002)",https://www.themoviedb.org/movie/10575,https://www.themoviedb.org/movie/10575/cast
7,Le Seigneur des anneaux : Les Deux Tours,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...,https://www.themoviedb.org/movie/121,https://www.themoviedb.org/movie/121/cast
8,Veronica Guerin (film),https://fr.wikipedia.org/wiki/Veronica_Guerin_...,https://www.themoviedb.org/movie/10629,https://www.themoviedb.org/movie/10629/cast
9,Coffee and Cigarettes,https://fr.wikipedia.org/wiki/Coffee_and_Cigar...,https://www.themoviedb.org/movie/883,https://www.themoviedb.org/movie/883/cast
10,Les Disparues,https://fr.wikipedia.org/wiki/Les_Disparues,https://www.themoviedb.org/movie/12146,https://www.themoviedb.org/movie/12146/cast
11,Le Seigneur des anneaux : Le Retour du roi,https://fr.wikipedia.org/wiki/Le_Seigneur_des_...,https://www.themoviedb.org/movie/122,https://www.themoviedb.org/movie/122/cast
12,La Vie aquatique,https://fr.wikipedia.org/wiki/La_Vie_aquatique,https://www.themoviedb.org/movie/421,https://www.themoviedb.org/movie/421/cast
13,Aviator,https://fr.wikipedia.org/wiki/Aviator,https://www.themoviedb.org/movie/2567,https://www.themoviedb.org/movie/2567/cast
14,"Little Fish (film, 2005)",https://fr.wikipedia.org/wiki/Little_Fish_(fil...,https://www.themoviedb.org/movie/9993,https://www.themoviedb.org/movie/9993/cast
15,"Babel (film, 2006)","https://fr.wikipedia.org/wiki/Babel_(film,_2006)",https://www.themoviedb.org/movie/1164,https://www.themoviedb.org/movie/1164/cast
16,The Good German,https://fr.wikipedia.org/wiki/The_Good_German,https://www.themoviedb.org/movie/182,https://www.themoviedb.org/movie/182/cast
17,Chronique d'un scandale,https://fr.wikipedia.org/wiki/Chronique_d%27un...,https://www.themoviedb.org/movie/1259,https://www.themoviedb.org/movie/1259/cast
18,Hot Fuzz,https://fr.wikipedia.org/wiki/Hot_Fuzz,https://www.themoviedb.org/movie/4638,https://www.themoviedb.org/movie/4638/cast
19,I'm Not There,https://fr.wikipedia.org/wiki/I%27m_Not_There,https://www.themoviedb.org/movie/3902,https://www.themoviedb.org/movie/3902/cast
20,Elizabeth : L'Âge d'or,https://fr.wikipedia.org/wiki/Elizabeth_:_L%27...,https://www.themoviedb.org/movie/4517,https://www.themoviedb.org/movie/4517/cast
21,Ponyo sur la falaise,https://fr.wikipedia.org/wiki/Ponyo_sur_la_fal...,https://www.themoviedb.org/movie/12429,https://www.themoviedb.org/movie/12429/cast
22,Indiana Jones et le Royaume du crâne de cristal,https://fr.wikipedia.org/wiki/Indiana_Jones_et...,https://www.themoviedb.org/movie/217,https://www.themoviedb.org/movie/217/cast
23,L'Étrange Histoire de Benjamin Button (film),https://fr.wikipedia.org/wiki/L%27%C3%89trange...,https://www.themoviedb.org/movie/4922,https://www.themoviedb.org/movie/4922/cast

2. La liste des acteurs d'un film se présente comme une liste ordonnée `ol` dans les pages TMDB. Scraper les pages de casting pour ajouter la liste des acteurs de chaque film dans une nouvelle colonne du dataframe `films`.

In [ ]:
# on récupère sur chaque page tmdb les infos sur le casting

3. Utiliser le résultat de la question précédente pour répondre à la question initiale : avec quels acteurs Cate Blanchett a-t-elle partagé l'affiche le plus souvent au cours des années 2000 ?